# This is a basic workflow to help you get started with Actions

name: Angular

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.1
        
      # Install dependencies
    - name: Install dependencies
      run: npm install
      working-directory: ChatClient/Presentation/Client/Presentation.Client
      
      # Check linting rules
      #- name: Lint
      #run: npm run lint
      #working-directory: ChatClient/Presentation/Client/Presentation.Client
      
      # Run build
    - name: Build
      run: npm run build --prod
      working-directory: ChatClient/Presentation/Client/Presentation.Client
      
      # Run unit tests
    - name: Test
      run: npm run test --browsers ChromeHeadless --watch=false
      working-directory: ChatClient/Presentation/Client/Presentation.Client
      
      # Run End-To-End tests
      #- name: E2E
      #run: npm run e2e -- --configuration=ci
      #working-directory: ChatClient/Presentation/Client/Presentation.Client
